#!/usr/bin/env bash
set -euo pipefail

echo "WORKSPACE=${RD_OPTION_WORKSPACE:-}"
echo "IMAGE=${RD_OPTION_IMAGE:-}"
echo "TAG=${RD_OPTION_TAG:-}"
echo "NAMESPACE=${RD_OPTION_NAMESPACE:-}"
echo "DEPLOYMENT=${RD_OPTION_DEPLOYMENT:-}"
echo "CONTAINER=${RD_OPTION_CONTAINER:-}"
echo "PORT=${RD_OPTION_PORT:-}"

WORKSPACE="${RD_OPTION_WORKSPACE}"
IMAGE="${RD_OPTION_IMAGE}"
TAG="${RD_OPTION_TAG}"
NAMESPACE="${RD_OPTION_NAMESPACE}"
DEPLOYMENT="${RD_OPTION_DEPLOYMENT}"
CONTAINER="${RD_OPTION_CONTAINER}"
PORT="${RD_OPTION_PORT:-8080}"

cd "${WORKSPACE}"

./k8s/deploy.sh \
  "${IMAGE}" \
  "${TAG}" \
  "${NAMESPACE}" \
  "${DEPLOYMENT}" \
  "${CONTAINER}" \
  "${PORT}"
